services:
  webansicht:
    image: a13r/webansicht
    build: .
    ports:
      - "3030:3030"
    links:
      - mongo
    restart: always
  mongo:
    image: mongo:4.0
    volumes:
      - mongo-db:/data
    ports:
      - "127.0.0.1:27017:27017"
    restart: always

volumes:
  mongo-db:
