services:
  webansicht:
    image: a13r/webansicht
    build: .
    ports:
      - "3030:3030"
    links:
      - mongo
    volumes:
      - ./config:/opt/webansicht/config
      - ./data/import:/import
    restart: always
  mongo:
    image: mongo:${MONGO_VERSION:-8.2}
    ports:
        - "127.0.0.1:27017:27017"
    volumes:
      - ./data/configdb:/data/configdb
      - ./data/db:/data/db
    restart: always
