version: "3"
services:
  webansicht:
    image: a13r/webansicht
    build: .
    ports:
      - "3030:3030"
    links:
      - mongo
    restart: always
  mongo:
    image: mongo
    volumes:
      - ./data:/data
    restart: always

